// Copyright (c) Pomelo Foundation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.TestUtilities;
using Pomelo.EntityFrameworkCore.MySql.FunctionalTests.TestUtilities;
using Pomelo.EntityFrameworkCore.MySql.Tests;
using Xunit;

namespace Pomelo.EntityFrameworkCore.MySql.FunctionalTests;

public class StructuralJsonMigrationsMySqlTest
    : StructuralJsonMigrationsTestBase<StructuralJsonMigrationsMySqlTest.MySqlFixture>
{
    public StructuralJsonMigrationsMySqlTest(MySqlFixture fixture)
        : base(fixture)
    {
    }

    protected override bool NoBackslashEscapes
        => false;

    public sealed class MySqlFixture : StructuralJsonMigrationsFixtureBase
    {
        protected override ITestStoreFactory TestStoreFactory
            => MySqlTestStoreFactory.Instance;
    }
}

public class StructuralJsonMigrationsMySqlNoBackslashEscapesTest
    : StructuralJsonMigrationsTestBase<StructuralJsonMigrationsMySqlNoBackslashEscapesTest.MySqlFixture>
{
    public StructuralJsonMigrationsMySqlNoBackslashEscapesTest(MySqlFixture fixture)
        : base(fixture)
    {
    }

    protected override bool NoBackslashEscapes
        => true;

    public sealed class MySqlFixture : StructuralJsonMigrationsFixtureBase
    {
        protected override string StoreName
            => "StructuralJsonMigrationsNBE";

        protected override ITestStoreFactory TestStoreFactory
            => MySqlTestStoreFactory.NoBackslashEscapesInstance;
    }
}

public abstract class StructuralJsonMigrationsTestBase<TFixture>(TFixture fixture)
    : IClassFixture<TFixture>
    where TFixture : StructuralJsonMigrationsFixtureBase, new()
{
    protected TFixture Fixture { get; } = fixture;

    protected virtual bool NoBackslashEscapes
        => false;

    [Fact]
    public void Structural_json_literals_use_provider_escaping()
    {
        using var context = Fixture.CreateContext();
        var literal = context.Model.GetRelationalModel().Tables
            .Single(table => table.Name == "Documents")
            .FindColumn("Settings")!
            .StoreTypeMapping
            .GenerateSqlLiteral(StructuralJsonMigrationData.InitialJson);

        var expected = AppConfig.ServerVersion.Supports.JsonDataTypeEmulation
            ? NoBackslashEscapes
                ? """'{"Description":"O''Reilly \\ archive — 初始 😀"}'"""
                : """'{"Description":"O''Reilly \\\\ archive — 初始 😀"}'"""
            : NoBackslashEscapes
                ? """CAST('{"Description":"O''Reilly \\ archive — 初始 😀"}' AS json)"""
                : """CAST('{"Description":"O''Reilly \\\\ archive — 初始 😀"}' AS json)""";

        Assert.Equal(expected, literal);
    }

    [Fact]
    public async Task Structural_json_literals_execute_on_the_configured_server()
    {
        await using var context = Fixture.CreateContext();
        var literal = context.Model.GetRelationalModel().Tables
            .Single(table => table.Name == "Documents")
            .FindColumn("Settings")!
            .StoreTypeMapping
            .GenerateSqlLiteral(StructuralJsonMigrationData.InitialJson);

        // The SQL literal is generated by the provider from a fixed test value.
        await context.Database.OpenConnectionAsync();
        await using var command = context.Database.GetDbConnection().CreateCommand();
        command.CommandText = "SELECT " + literal + " AS `Value`";
        var result = (string)await command.ExecuteScalarAsync();

        Assert.Equal(
            AppConfig.ServerVersion.Supports.JsonDataTypeEmulation
                ? StructuralJsonMigrationData.InitialJson
                : StructuralJsonMigrationData.MySqlCanonicalJson,
            result);
    }

    [Fact]
    public async Task Migrations_insert_and_update_structural_json_data()
    {
        await using (var context = Fixture.CreateContext())
        {
            await context.Database.EnsureDeletedAsync();
            Assert.Equal(
                "json",
                context.Model.GetRelationalModel().Tables
                    .Single(table => table.Name == "Documents")
                    .FindColumn("Settings")!
                    .StoreType);

            await context.Database.MigrateAsync("20260902000100_CreateStructuralJsonDocuments");
        }

        await using (var context = Fixture.CreateContext())
        {
            var document = await context.Documents.SingleAsync();
            Assert.Equal(StructuralJsonMigrationData.InitialDescription, document.Settings!.Description);

            await context.Database.MigrateAsync("20260902000200_UpdateStructuralJsonDocuments");
        }

        await using var verificationContext = Fixture.CreateContext();
        var updatedDocument = await verificationContext.Documents.SingleAsync();
        Assert.Equal(string.Empty, updatedDocument.Settings!.Description);
    }
}

internal static class StructuralJsonMigrationData
{
    internal const string InitialDescription = "O'Reilly \\ archive — 初始 😀";
    internal const string InitialJson = """{"Description":"O'Reilly \\ archive — 初始 😀"}""";
    internal const string MySqlCanonicalJson = """{"Description": "O'Reilly \\ archive — 初始 😀"}""";
    internal const string UpdatedJson = """{"Description":""}""";
}

public sealed class StructuralJsonMigrationsContext(DbContextOptions options) : DbContext(options)
{
    public DbSet<StructuralJsonMigrationDocument> Documents
        => Set<StructuralJsonMigrationDocument>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<StructuralJsonMigrationDocument>(builder =>
        {
            builder.Property(document => document.Id).ValueGeneratedNever();
            builder.OwnsOne(
                document => document.Settings,
                ownedBuilder => ownedBuilder.ToJson());
        });
}

public sealed class StructuralJsonMigrationDocument
{
    public int Id { get; set; }
    public StructuralJsonMigrationSettings Settings { get; set; } = null!;
}

public sealed class StructuralJsonMigrationSettings
{
    public string Description { get; set; } = null!;
}

public abstract class StructuralJsonMigrationsFixtureBase
    : SharedStoreFixtureBase<StructuralJsonMigrationsContext>
{
    protected override string StoreName
        => "StructuralJsonMigrationsMySqlTest";

    protected override Task SeedAsync(StructuralJsonMigrationsContext context)
        => Task.CompletedTask;
}

[DbContext(typeof(StructuralJsonMigrationsContext))]
[Migration("20260902000100_CreateStructuralJsonDocuments")]
internal sealed class CreateStructuralJsonDocumentsMigration : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Documents",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false),
                Settings = table.Column<string>(type: "json", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Documents", x => x.Id);
            });

        migrationBuilder.InsertData(
            table: "Documents",
            columns: new[] { "Id", "Settings" },
            columnTypes: new[] { "int", "json" },
            values: new object[,] { { 1, StructuralJsonMigrationData.InitialJson } });
    }

    protected override void Down(MigrationBuilder migrationBuilder)
        => migrationBuilder.DropTable("Documents");
}

[DbContext(typeof(StructuralJsonMigrationsContext))]
[Migration("20260902000200_UpdateStructuralJsonDocuments")]
internal sealed class UpdateStructuralJsonDocumentsMigration : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
        => migrationBuilder.UpdateData(
            table: "Documents",
            keyColumns: new[] { "Id" },
            keyColumnTypes: new[] { "int" },
            keyValues: new object[,] { { 1 } },
            columns: new[] { "Settings" },
            columnTypes: new[] { "json" },
            values: new object[,] { { StructuralJsonMigrationData.UpdatedJson } });

    protected override void Down(MigrationBuilder migrationBuilder)
        => migrationBuilder.UpdateData(
            table: "Documents",
            keyColumns: new[] { "Id" },
            keyColumnTypes: new[] { "int" },
            keyValues: new object[,] { { 1 } },
            columns: new[] { "Settings" },
            columnTypes: new[] { "json" },
            values: new object[,] { { StructuralJsonMigrationData.InitialJson } });
}
